language: php

sudo: false

php:
  - 7.2

before_script:
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
- phpenv rehash
- php artisan key:generate
- nvm install 10.9.0
- npm ci

script:
- vendor/bin/phpunit --coverage-text
- npm run test-travis