language: php

sudo: false

php:
  - 7.2

cache:
  directories:
  - ~/.npm

before_script:
- composer self-update
- composer install --no-interaction
- cp .env.travis .env
- phpenv rehash
- php artisan key:generate
- nvm install 10.9.0
- npm ci
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- vendor/bin/phpunit --coverage-text
- npm run test-travis